### ISSUE TITLE
Upcoming Changes

### ISSUE THREAD

**Issue by turtleisaac** [SaltContainer/PokemonPlatinumMapRandoTracker#1]
Hi, I'm one of the devs for the warp randomizer. 

First off, thanks a ton for making this! It's easy to use and is much better than a spreadsheet when it comes to keeping track of stuff. I just thought I'd let you know that in upcoming versions, the Ribbon Syndicate entrance in the resort area will be a randomized warp. This hasn't taken effect yet, but the next release (probably sometime in the next few days) will have this change.

**Comment by SaltContainer** [comment]
Hi, thank you for the kind words! It's been very fun working on the trackers!

Thank you for the heads up on the update, I'll work on that when I have some time.

**Comment by turtleisaac** [comment]
The villa entrance has been randomized now too btw for future versions. It's just that the villa interior won't be randomized to anywhere.

**Comment by SaltContainer** [comment]
Added the warps in 56238f0. I'll keep on eye on when the UWP update comes out and I'll make a new release then.
